[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meshagent-create-python-task-queue-dashboard"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "aiohttp[speedups]~=3.13.0",
  "meshagent-api==__MESHAGENT_CLIENT_VERSION__",
]

[tool.setuptools]
py-modules = ["server"]
